---
- name: Update and Upgrade Ubuntu Server
  hosts: 172.31.91.198
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        
    - name: Upgrade packages
      apt:
        upgrade: dist
        
    - name: Clean apt cache
      apt:
        autoclean: yes
